### ISSUE TITLE
crashes while using library and install game functions  

### ISSUE THREAD

**Issue by yamariha** [rauenzi/BetterDiscordApp#207]
my discord crashes everytime i push library tab or install a game tried uninstalling and reinstalling  both basic and betterdiscord  even deleted folder no plugins or scripts in use or installed  (this dosnt happen with basic discord)  and i get the same problem

**Comment by yamariha** [comment]
happens to me on all 3 versions  stable, canery, ptb  here is wat happens    [https://gyazo.com/e81f3e170c17746dcb839fa5ec07a10b](url)

errors 
[https://cdn.discordapp.com/attachments/119918741516451840/588183493087985676/unknown.png](url)

**Comment by NFLD99** [comment]
![unknown](https://user-images.githubusercontent.com/24623601/59342894-41bfd080-8ce5-11e9-98be-10edd3043931.png)
[Reuploaded image incase discord cdn decides to fail]

**Comment by mattcapaz** [comment]
So this started to happen to me too out of "no where", **I can't access my Library Tab** I don't really why's this happening at all, I tried uninstalling Discord, installing Discord didn't work it out. Tried to Repair BD didn't work, Tried to uninstall it and install it again, didn't work too. And It's not because of Discord since, when I access Regular Discord without BDA, it works great, and I can access my Library Tab, when I have BDA it's the only tab, that I can't seem to open, without getting that screen to pop-up.

**Comment by rauenzi** [comment]
I've seen a few people with this issue but I'm unable to reproduce and can't get to the bottom of it.

**Comment by NFLD99** [comment]
Maybe it's a game causing it, those with the issue can you please let us know what game(s) you installed before the bug happened?

**Comment by just-Addict** [comment]
Prior to current issue with all 3 Discord versions crashing on installing a game I had installed:

Metro Last Light Redux
Metro 2033 Reduc
Bioshock Remastered
Bioshock 2 Remastered
Mafia
Abzu
Inside
Lost Horizon
Kathy Rain
Star Wars Dark Forces
Star Wars Jedi Knight Dark Forces II
Star Wars Jedi Knight Jedi Academy
Star Wars Jedi Knight II Jedi Outcast

There were also a few non-game folders in the Game Library folder but even moving those out of the library folder didn't fix things
