### ISSUE TITLE
[Bug] Latest Canary removes install and not reinstalling

### ISSUE THREAD

**Issue by Infinidoge** [rauenzi/BetterDiscordApp#273]
**Describe the Bug**
Latest Canary removes installation and prevents reinstall (installer runs, no effect on Discord)

**To Reproduce**
Update to latest Canary, 
Run installer

**Expected Behavior**
Should install to Canary

**Screenshots**

**Discord Version**
Release Channel: canary, Build Number: 49167

**Additional Context**

**Comment by luxidoptera** [comment]
This seems to be occurring on PTB as well.

**Comment by NFLD99** [comment]
Can reproduce. Canary & PTB

**Comment by mappleaf** [comment]
Same.

**Comment by ValliteKing** [comment]
Yep, same story for me too. Well this sucks... Guess we're waiting.

**Comment by RaXorX** [comment]
How do you check the build number though? Sorry, but I only know about the 0.0.258.0 (the version that pops up in the executable details)
And yes, BD was working fine until just today. I'm not sure what ticked it off. I was having some crashes in some server for apparently no reason and instead of disabling the plugins manually, I just removed the plugins and themes folder. 

The server worked, but trying to put the themes and plugins back had no effect. (I'm not sure if discord was at build 49167 or not, but it was updated to the 258 version)
Reinstalling BD or discord had no effect.

**Comment by Insan1ty0ne** [comment]
I am having the exact same issue:

Release Channel: canary, Build Number: 49174, Host: 0.0.258

Re-installing BBD has zero effect and BBD will not launch with Discord.

**Comment by THEMIO90000** [comment]
This is the end of Badadged Discord?

**Comment by master3395** [comment]
I've tried all Discord version, and BDD is gone from all.
And yes, the installer doesn't work on any of these versions anymore.

0.0.305 - Discord
0.0.258 - Discord Canary
0.0.49 - PTB

**Comment by ScarXLXX** [comment]
Same issue here. Waiting for a fix, hopefully.

**Comment by idontwanttogotobed** [comment]
> This is the end of BandagedDiscord?

Hope not!

**Comment by rauenzi** [comment]
I am away for the weekend, asking if this is the end is being overly dramatic. I will get to it when I am back.

Locking this as we don't need a thousand "same" comments.
