### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by huskiewantscustom** [rauenzi/BetterDiscordApp#353]
When I tried to open the BandagedBD application on my MacBook (macOS Catalina), it says it "cannot be opened because the developer cannot be verified." And "macOS cannot verify that this app is free from malware." Help- what should I do? 
<img width="415" alt="Screen Shot 2020-05-09 at 5 33 17 PM" src="https://user-images.githubusercontent.com/65097498/81488247-2cb43000-921b-11ea-9407-7589a836c841.png">

**Comment by rauenzi** [comment]
This is an option that you have to disable on your computer.

**Comment by djlo03** [comment]
![](https://user-images.githubusercontent.com/65097498/81488247-2cb43000-921b-11ea-9407-7589a836c841.png)

I have the same problem and I do no know what setting to disable in order to fix this. can someone please help

**Comment by JessicaSachs** [comment]
Some instructions as of OSX Monterey

1. Open the Apple menu, and click System Preferences.
2. Click Security & Privacy.
3. Click the General tab.
4. Click the lock in the lower right corner of the window.
5. Enter your username and password when prompted, and click Unlock.
6. Click the App Store and Identified Developers radial button.
7. Look for “(App Name) was blocked from opening because it is not from an identified developer” and click Open Anyway. (In older versions of macOS, you could click Anywhere and then click Allow From Anywhere.)
8. Try rerunning the app.
