### ISSUE TITLE
[Feature] Silent Install/Uninstall

### ISSUE THREAD

**Issue by virtualex-itv** [rauenzi/BetterDiscordApp#382]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Silent Install/Uninstall parameters

**Additional context**
I'd like to be able to script this into a silent install for my machine

**Comment by rauenzi** [comment]
You can create your own script that follows the manual installation procedures found on the README. However, the idea of a "silent" installer sound a bit nefarious.

**Comment by virtualex-itv** [comment]
OK, the intent was to also be able to publish a package on chocolatey which would need a silent way of installing.  I suppose I could do this using the manual install process, but would be much easier if a native parameter was available

**Comment by rauenzi** [comment]
As this is open source, you can create your own script to publish there, however I don't intend on creating either a silent installation script or a chocolatey package.

> would be much easier if a native parameter was available

What do you mean?

**Comment by AliceDTRH** [comment]
I imagine they meant a command line parameter that can be used with the installer to make it quiet like is common with many installers.

**Comment by virtualex-itv** [comment]
> I imagine they meant a command line parameter that can be used with the installer to make it quiet like is common with many installers.

exactly.

**Comment by rauenzi** [comment]
But it is not a command line installer, so what would this "quiet" do for a GUI application?

**Comment by rauenzi** [comment]
Also if you are referring to the command line linux installer, that is not managed or created by me, and the issue should be opened over there. https://github.com/bb010g/betterdiscordctl

**Comment by AliceDTRH** [comment]
It would make it so no user interaction is needed during the installation but you already specified you don't want to make that yourself. Is the installer source code available?

**Comment by rauenzi** [comment]
Due to the nature of this application (being a modification of existing) it is sometimes necessary to get user input about the location of their Discord installation. (Due to multiple install locations, multiple version, unusual install location, etc)

To answer your question, yes the installer source is available at https://github.com/rauenzi/BBDInstaller and as I said above, it is a GUI installer made with WinForms, so it is not a command line compatible tool. That's why I pointed to the linux installer which is a command line tool, and the manual installation instructions which could be made into a script form.

**Comment by AliceDTRH** [comment]
Thank you for the information, using this it should indeed be possible to create a silent installer.  :smiley:

**Comment by rauenzi** [comment]
You can do this now using the `npm inject` script
