### ISSUE TITLE
[Bug] Popout Player Forever Loading

### ISSUE THREAD

**Issue by Xelus22** [rauenzi/BetterDiscordApp#417]
**Describe the Bug**

Screensharing or video chat does works fine when NOT popped out. However once popped out, it loads forever and doesn't show video.

**To Reproduce**

Get in call, get another person to video chat, popout player.

**Expected Behavior**

Seeing video of myself and the other people in call.

**Screenshots**

![image](https://user-images.githubusercontent.com/17491233/89615989-f003dd80-d8ca-11ea-982b-5c716776d6bd.png)

**Discord Version**

Stable

**Additional Context**

**Comment by cdantetho** [comment]
**I'm also getting this issue.**
I believe this bug appeared when I had to get the new installer and re-install to my stable Discord.

**Discord Version:**
Stable 65245 (7d159d7)
BBD 0.3.5
Host 0.0.307
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Comment by An00nymushun** [comment]
The problem is that even though the window doesn't have its own preload script, it leaks through from the main window somehow while the enableRemoteModule setting doesn't.

You can restore the original preload setting like this `process.electronBinding("command_line").appendSwitch("preload", currentWindow.__originalPreload);`

Look at the bottom of the attached file to see how it can be implemented.

[preload.zip](https://github.com/rauenzi/BetterDiscordApp/files/5081320/preload.zip)

**Comment by rauenzi** [comment]
Hey thanks for finding this. Looks like Discord creates the popout window using the current webContents instead of an options object, but I'm not entirely certain why the preload itself is run again in this case. I am still looking into that part of things. Is there any reason you check if `process` is undefined?

**Comment by rauenzi** [comment]
@Xelus22 Can you try reinstalling BD and then see if the issue persists?

**Comment by eeemmmddd** [comment]
I am the user who wrote the post https://github.com/rauenzi/BetterDiscordApp/issues/423. Even if I reinstall both discord and bd several times, the same symptom appears.

**Comment by rauenzi** [comment]
Can you ensure that after installing BD your injector is up to date? Install BD on Discord Stable then find this file: `%localappdata%\Discord\app-0.0.307\resources\app\betterdiscord\preload.js` and see if you can find the line `process.electronBinding("command_line").appendSwitch("preload", currentWindow.__originalPreload);` toward the bottom of the file. If it isn't there, your injector isn't the latest version.

**Comment by Xelus22** [comment]
> @Xelus22 Can you try reinstalling BD and then see if the issue persists?
@rauenzi 
I have just tested and it works great 💯 now.

Thanks a lot 👍

**Comment by An00nymushun** [comment]
Ah, there is no specific reason to check process, it's just a habit of mine because of all the internal electron changes that happened in the past.
