### ISSUE TITLE
[Bug] Windows Auto Installer link downloads an old version of the installer

### ISSUE THREAD

**Issue by Grelo4ka** [rauenzi/BetterDiscordApp#430]
**Describe the Bug**

In `README.md`, the Windows Auto Installer link (`https://github.com/rauenzi/BetterDiscordApp/releases/latest/download/BandagedBD_Windows.exe`) is outdated. As soon as one opens the installer, there is a prompt saying "Update Available!, There is a newer version of the installer available (v1.0.5). Would you like to download it now?".

**To Reproduce**

1. Go to https://github.com/rauenzi/BetterDiscordApp#windows
2. Click the link
3. Open the downloaded `BandagedBD_Windows.exe` file 

**Expected Behavior**

If the newest version of the installer is v1.0.5, I expect the link to download v1.0.5, not v1.0.4

**Screenshots**

![BandagedBD_Windows_JKhwWUajnD](https://user-images.githubusercontent.com/62602570/90751240-27648800-e2d6-11ea-8157-8c58049c177c.png)

**Discord Version**

N/A

**Additional Context**

I haven't tested macOS and Linux links

**Comment by apwhitelaw** [comment]
> 
> 
> > Are you sure you didn't download the new one and run the old one?
> 
> Yes, I am sure.

I think he might have been referring to me when I said I specifically downloaded v1.0.5 and still got that popup.

> 
> 
> Are you sure you didn't download the new one and run the old one?

After testing this out again, I can confirm that I ran that correct file that is expected to be v1.0.5, and still got that popup. I actually didn't realize before, but the installer shows the version in the title of the window. When you download and run v1.0.5, the window still says v1.0.4. So either the wrong file is linked, or it has not been updated to recognize that it is actually v1.0.5.

I'm not sure how the application determines that there is a newer version, so I'm not sure if it is the entirely wrong file, or if it is simply just that it wasn't updated to show that it actually is v1.0.5.

**Comment by rauenzi** [comment]
It should link you to the installer found here: https://github.com/rauenzi/BBDInstaller/releases/latest/ which is indeed 1.0.5 and downloading and running that shows 1.0.5

**Comment by apwhitelaw** [comment]
Okay now I'm a bit confused. What is the difference between BetterDiscordApp and BBDInstaller? We are on the github page for BetterDiscordApp and the latest release says v1.0.5 but we are getting v1.0.4 installer.

You just linked a file from BBDInstaller, which has the correct file. If BetterDiscordApp is the main repo and the intention is for users to install it from the BBDInstaller, the other repo does not link to BBDInstaller.

**Comment by rauenzi** [comment]
The releases page here only contains the installer because that's how it always was before I forked it so that's where people went. But it doesn't make sense for the installer to live there hence the other repo. Yes the README here does still temporarily link to the releases here. But when you run the installer and it prompts you to download the latest one, it will take you to the other repo to download the latest version.

**Comment by apwhitelaw** [comment]
Okay that makes sense. Somehow when it first prompted me there was a newer version, I thought I hit yes and downloaded the file that it brought me to, but the files are named slightly differently so it's obviously the wrong one, and it appears that I must have just tried to manually download it again. 

After running the installer again, I can confirm that pressing 'Yes' brings me to the right download. Sorry about that, but thanks for the explanation because it helps to understand why it is setup this way.

**Comment by rauenzi** [comment]
I've updated the README to link to the other repo now as well.
