### ISSUE TITLE
[Bug] Game freezes when BD checks for plugin updates (linux)

### ISSUE THREAD

**Issue by MasterIO02** [rauenzi/BetterDiscordApp#436]
**Describe the Bug**
Hello, I'm having a problem with BD, every time it checks for plugin updates (I think because every time discord freezes too and I'm having BD notifications about plugins), Discord uses my CPU up to 30% for a couple of seconds, causing freezes in some games, and that's a bit annoying.
I'm using Linux (Pop! OS 20.04), on Windows 10 the problem is there too, but with less apparent freezes for games.
I haven't found a settings allowing me to disable those checks for plugins.

**Discord Version**
Stable 65952, BBD 0.3.5

Thanks!

**Comment by rauenzi** [comment]
Hi, there is no setting for it because BBD does not check for plugin updates. That's a part of the plugin libraries BDFDB and ZeresPluginLibrary. So any plugins by myself or DevilBro will cause the update check to be added. Although it shouldn't be causing freezes. I would recommend disabling any plugins by DevilBro and reloading and see if the issue persists.

But like I said, this is not something BD does so I am closing the issue.

**Comment by MasterIO02** [comment]
Thanks for the reply! Will do that and test.
