### ISSUE TITLE
[Feature] Support loading ESModule Plugins

### ISSUE THREAD

**Issue by emmachase** [rauenzi/BetterDiscordApp#452]
**Is your feature request related to a problem? Please describe.**

My development environment for writing plugins for BBD consists of TypeScript for language features and Webpack for bundling. The plugin loader is not exactly forgiving when it comes to minor differences between plugin layout. Specifically, the standard in typescript is to do something like the following:

```typescript
export default class MyPlugin {
    // ...
}
```

Once transpiled (assuming "ESNext" module target), this essentially gets converted to something like:

```javascript
exports.default = class MyPlugin { /*...*/ }
```

This format is **not** recognized by the plugin loader and will **fail**.

There exists the "commonjs" module target, which can generate the correct code for plugin loading; however, just setting it to `commonjs` alone is not enough. Additionally you have to rewrite the export like so:

```typescript
class MyPlugin { /*...*/ }

export = MyPlugin;
```

This is inconvenient for a number of reasons: 
1. This is legacy syntax, default exports are recommended/preferred.
2. This syntax is incompatible with the "ESNext" module target, which I need to use because
3. Webpack's tree-shaking does not work unless the module format is an ES variant, commonjs will disable the tree-shaker because `tsc` will not transpile the modules into a format the tree-shaker can work with. (In my case this leads to extremely bloated plugin files with lots of unnecessary code)

**Describe the feature you'd like**

More flexible support for loading modules, specifically this just means doing something like the following:
```javascript
const module = howeverTheModulesAreEvaluated(...);
const pluginClass = module.default || module;
const instance = new pluginClass();
```

**Additional context**

I'm more than happy to submit a PR for this, but I do not want to if I don't know it will be considered. I am wondering if there's a reason that this is not already supported.

**Comment by rauenzi** [comment]
> Additionally you have to rewrite the export like so

This should not be necessary, I currently don't do this myself for my plugin library. You can see here https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js#L34 although I admit I am using `commonjs2` as a target.

> This is legacy syntax, default exports are recommended/preferred.

That's preferred by things using emcascript modules for sure, however those are [still in the experimental support phase](https://nodejs.org/api/esm.html#esm_modules_ecmascript_modules) in node. And their section on commonjs module still shows the usage of `module.exports` as opposed to `exports.default`

> This syntax is incompatible with the "ESNext" module target, which I need to use because Webpack's tree-shaking does not work unless the module format is an ES variant [...]

This I agree can be quite annoying. I can add support for `exports.default`. Ideally truly supporting ESM would come in the rewrite because the current plugin system is so poor.

> I am wondering if there's a reason that this is not already supported.

Because the original version of BD (as written by Jiiks) didn't even make use of the concept of modules and relied on names of functions/classes matching what was in the META, I have slowly moved devs to use actual modules without breaking backwards compatibility.

I will try to get around to adding the `exports.default` as an option in the next day or so, but like I said, rewriting the exports should not be necessary either.

**Comment by emmachase** [comment]
> > Additionally you have to rewrite the export like so
>
> This should not be necessary

It is normally, it seems you get around this by doing this:
```js
output: {
  libraryExport: "default"
}
```

Which is nice but shouldn't be necessary.

> still shows the usage of `module.exports` as opposed to `exports.default`

My apologies that was a miscommunication on my part. I meant `module.exports.default` but the point is moot.

> Ideally truly supporting ESM would come in the rewrite because the current plugin system is so poor.

Ah I wasn't aware that this project was undergoing a rewrite, neat. Though it would be nice to have this feature sooner than I imagine it will be until that rewrite is finished.


Thanks,
~Emma

**Comment by rauenzi** [comment]
> Which is nice but shouldn't be necessary.

To be fair, if it's required by the system you are integrating into, it's necessary 😉 Also there must have been a reason for webpack to add it as a feature--likely systems similar to this.

> I meant `module.exports.default` but the point is moot.

I'm still not sure where that's defined as a recommendation or preference.

> Ah I wasn't aware that this project was undergoing a rewrite

Well rewrite attempt number 3 or so... they always seem to putter out, but this one isn't as drastic so it should be alright.

I have a local change ready to accommodate `exports.default`/`module.exports.default` but I'll probably test it for a bit before pushing.

**Comment by emmachase** [comment]
Fair points, thanks for looking at this.
