### ISSUE TITLE
Crashes after starting

### ISSUE THREAD

**Issue by MacGyverPY** [rauenzi/BetterDiscordApp#556]
Yesterday no issues, today, i started my machine and BD loaded, loaded the plugins..etc then it showed discord...friends..channells..etc for a split second then crashed "awkward moment"

Reloading the app is what reproduces it
- tried reinstalling BD using different options, still crashing
- Noticed, if i click on FRIENDS it wont crash, i can go into settings, click every sub category, EXCEPT appearance... appearance CRASHES instantly.

Stable 76069 (602c8e4)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Expected Behavior**
To load and work like normal

**Screenshots**
<a href="https://ibb.co/Q8WjnVQ"><img src="https://i.ibb.co/Q8WjnVQ/Capture.png" alt="Capture" border="0"></a>

**Discord Version**
STABLE

**Additional Context**
This was working fine till today, just about 30min ago... nothing has changed, i didnt mess around with BD or add any plugins.. i tried removing the LAST plugin, it loaded... but nope. still crashed.

is there a Plugin, that reports Crashes, in detail
like, Last plugin loaded before crash..etc- this way for some of us, we can fix the simple things without nagging you

**Comment by PStreb** [comment]
i have this too
![Uploading Снимок экрана 2021-02-05 в 23.53.57.png…]()

**Comment by chiumax** [comment]
same here

**Comment by MacGyverPY** [comment]
```css
.UPDATE!
```
uninstalled BD (completely)
ran Discord Vanilla... Worked...
Installed BD- working...
installing Plugins now...

**Comment by l0c4lh057** [comment]
When the issue only persists when installing ZeresPluginLibrary I'd assume that it is a plugin using it bc afaik the library itself does not crash. Due to changes in discord two of my plugins cause a discord crash when using discord PTB or Canary (maybe the change already hit discord stable? idk): ChannelTabs and TypingIndicator. My first guess is that it is one of those two plugins. They already got updated but you need to update them manually if you have them.

If you dont have either of those two or redownloading them does not fix it then try either opening the console (ctrl + shift + i) and looking for error messages or just removing plugins until it works and then telling us which one it is.

**Comment by MacGyverPY** [comment]
i think its the COLOR TEXT as per that noted bug since discortd update...

**Comment by rauenzi** [comment]
Fixed by #573
