### ISSUE TITLE
[Bug]  When I install discord betterdiscord it doesn't work properly and it loads that I'm in the browser.

### ISSUE THREAD

**Issue by xDMKK** [rauenzi/BetterDiscordApp#608]
When I install discordbetter discord I load as if I use the settings. I tried everything ... I reinstalled discord, reinstalled discordbetter and nothing helped

![Zrzut ekranu 2021-03-26 223351](https://user-images.githubusercontent.com/81445555/112694838-5a31b880-8e83-11eb-8a29-a1e566261329.png)

**Discord Version**
Stable 80597

**Comment by xDMKK** [comment]
I closed because I succeeded, but after about 5 minutes discord made the updates itself and discordbetter disappeared. And discord has switched to browser mode

**Comment by xDMKK** [comment]
I noticed there are doubled lines. as if discord better was there, but it didn't work.
![Uploading Zrzut ekranu 2021-03-26 225234.png…]()

**Comment by Drip9r** [comment]
Try deleting all source/trace files and reinstall. This should fix it.

**Comment by Orangian** [comment]
Same issue here, even when removing. I'm on Manjaro Linux with the discord app from the official repos. Flatpak has same issue.

**Comment by xDMKK** [comment]
I've tried everything. And nothing helped. I deleted all discord files on my computer as well as discordbetter. There is a mistake all the time. And if you manage to install it, after 5 minutes discord automatically updates and all discordbetter functions disappear

**Comment by 4n0nct** [comment]
> Try deleting all source/trace files and reinstall. This should fix it.
> 
> Also, this seems to only be a bug to mainly the PTB and Canary versions.
It does that for the main version too.
The best thing to do is just to uninstall betterdiscord, it fix this "browser" problem.



> I've tried everything.
just uninstall betterdiscord, you don't need to delete any file.
If you use betterdiscordctl then it's simple as using it while discord is opened with this command:
betterdiscordctl uninstall
then it will kill the discord process, restart discord and it's now detected as a desktop app.


> all discordbetter functions disappear

Yes it's broken with the last version, if you try to use it won't work and you discord will be the browser version, don't use it for now, just uninstall it until it's fixed by bd.

**Comment by xDMKK** [comment]
Thank you very much! I will be waiting impatiently.

**Comment by santiyounger** [comment]
I have the same problem, thanks for the update @4n0nct I'll also be looking forward for this to be solve to try it again. 

Would appreciate any updates once this is solve to test things again
Thank you!

**Comment by LividJava** [comment]
#600

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer
