### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JustAce0** [rauenzi/BetterDiscordApp#617]
**Describe the Bug**
After latest update i had to reinstal BD and after it discord changed into Browser version

**To Reproduce**
Just instal BD on latest patch using .exe

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/81614300/112951613-d35b3500-913b-11eb-99b5-3d132fb47cdb.png)

**Discord Version**
Stable

**Additional Context**
I just unstaled new discord update lul

**Comment by matoqueimado** [comment]
same

**Comment by CharlieEurope72** [comment]
Same for me. On Windows it only breaks when installing the latest patch. I uninstalled Discord entirely and reinstalled it. I immediately installed Better Discord and it worked. There is an icon on the top where you can install the latest discord patch and that seems to be what is breaking it since when I reinstalled Better Discord running the latest patch it didn't work.

**Comment by LoganDark** [comment]
Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.

**Comment by rauenzi** [comment]
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer
