### ISSUE TITLE
Themes setting missing [Bug]

### ISSUE THREAD

**Issue by EndZakuro** [rauenzi/BetterDiscordApp#727]
After Install the new version of better discord, themes that apply wasn't the one I download before. And then, my themes setting missing
![Screenshot 2021-04-23 121654](https://user-images.githubusercontent.com/81846635/115817705-f40e6600-a42d-11eb-8063-d5225f38feac.png)

**Comment by rauenzi** [comment]
Please rename this folder `%appdata%\BetterDiscord` to something else as a backup and reinstall BD.

**Comment by EndZakuro** [comment]
I already reinstall many times but still , the themes missing

**Comment by jaydenquilay** [comment]
This should fix it:

1. Put all your themes in a different folder. [On your desktop for example]

2. Restart Discord. [Ctrl + R]

3. Put your themes back, it should show up.

[Since Canary doesn't work at the moment, I'm using PTB.]
[Also not sure if anyone else figured this out, just came back to post this.]

**Comment by GEOEGII555** [comment]
One of your themes might just hide this setting to don't allow disabling it via `display: none;`
