### ISSUE TITLE
[Feature] Colored Border on offical plugins that get updates

### ISSUE THREAD

**Issue by siltentassasin** [rauenzi/BetterDiscordApp#737]
I think it would be a very nice and good feature, to add 
a colored (e.g. blue, ca 2-7px) border the plugins in the settings tab, if they are offical supported and get updates,
e.g. orage if they don't get updates and are offical ... Maybe optional enablable in the settings

**Comment by Tropix126** [comment]
At the moment this is out of scope, because plugins and themes are nothing more than static JS and CSS files, and there is very little data linked to them aside from that in the META. Once our new website is out, we will be able to use this data for officially verified plugins in the site's repository by checking the file hash. That being said, I doubt it will be a border, but likely a warning badge/modal on unofficial plugins.

**Comment by rauenzi** [comment]
See what Tropical said above.
