### ISSUE TITLE
[Feature] Class normalizer

### ISSUE THREAD

**Issue by DorCoMaNdO** [rauenzi/BetterDiscordApp#750]
Is there a reason it was removed with update 1.1.0? I've used it for custom CSS styling and I now see it's gone with many of my CSS changes no longer working.

**Comment by dav1312** [comment]
You shouldn't have been using them in the first place, they have been deprecated for years.
Zere has been warning about it for a very long time, asking developers to update their themes because at some point they were going to be removed.

![image](https://user-images.githubusercontent.com/63931154/117010206-dc1bc980-acec-11eb-9b62-0a4d77b63c71.png)

**Comment by DorCoMaNdO** [comment]
A deprecation notice within the settings would've been appreciated, I don't frequent the BetterDiscord server and I don't think that's unreasonable, instead it was simply removed without warning and I had to figure out why.
The only valid point in the screenshot is 4 as it's a direct alternative (though performance wise I suspect it might not be as efficient), while 1 is irrelevant as I use my own custom CSS, don't care about other platforms I don't use, I don't share the changes, 2 is not something I've come across for my use case in the long term, only while creating a new modification, which connects to 3, where I simply filter to the elements I do want to target with other selectors.

**Comment by rauenzi** [comment]
The comment by dav1312 and my comment here https://github.com/rauenzi/BetterDiscordAddons/issues/377#issuecomment-833955939 are how I feel about it. They have been discouraged for a long time and deprecated last year with months of notice to the plugin/theme developers.
